Applications/Models/DTDL.cs

namespace UACloudTwin.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;

    public class DTDL
    {
        [JsonProperty("@context")]
        public string context { get; set; }

        [JsonProperty("@id")]
        public string id { get; set; }

        [JsonProperty("@type")]
        public string type { get; set; }

        public string displayName { get; set; }

        public string description { get; set; }

        public string comment { get; set; }

        public List<Content> contents { get; set; }

        public List<string> extends { get;set; }

        public string schemas { get; set; }
    }

    public class Content
    {
        [JsonProperty("@type")]
        public string type { get; set; }

        [JsonProperty("@id")]
        public string id { get; set; }

        public bool writable { get; set; }

        public object schema { get; set; }

        public string name { get; set; }

        public string displayName { get; set; }

        public string description { get; set; }

        public string comment { get; set; }

        public string target { get; set; }
    }

    public class FlattenedModel
    {
        public string context { get; set; }

        public string id { get; set; }

        public string type { get; set; }

        public string displayname { get; set; }

        public string description { get; set; }

        public string comment { get; set; }

        public string contenttype { get; set; }

        public string contentid { get; set; }

        public bool writable { get; set; }

        public object schema { get; set; }

        public string contentname { get; set; }

        public string contentdisplayname { get; set; }

        public string contentdescription { get; set; }

        public string contentcomment { get; set; }

        public string target { get; set; }

        public string extends { get; set; }

        public string schemas { get; set; }
    }
}

Applications/Models/SetupModel.cs
namespace UACloudTwin.Models
{
    public class SetupModel
    {
         public string StatusMessage { get; set; }
    }
}

Applications/Models/StatusModel.cs
namespace UACloudTwin.Models
{
    public class StatusModel
    {
        public string Status { get; set; }
    }
}

Applications/Controllers/AuthController.cs

namespace UACloudTwin.Controllers
{
    using Microsoft.AspNetCore.Authentication;
    using Microsoft.AspNetCore.Authentication.Cookies;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using System;
    using System.Collections.Generic;
    using System.Security.Claims;
    using UACloudTwin.Models;

    public class AuthController : Controller
    {
        public IActionResult Index(string returnUrl)
        {
            return View(new StatusModel() { Status = returnUrl });
        }

        public IActionResult Login(string username, string password, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                if (!AuthenticateUser(username, password))
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                   return View("Error", new StatusModel() { Status = "Access Denied!" });
                }

                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, username),
                    new Claim(ClaimTypes.Role, "Administrator"),
                };

                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                var authProperties = new AuthenticationProperties
                {
                    IsPersistent = true,
                    IssuedUtc = DateTimeOffset.UtcNow
                };

                HttpContext.SignInAsync(
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(claimsIdentity),
                    authProperties).GetAwaiter().GetResult();

                return Redirect(returnUrl);
            }

            return View();
        }

        private bool AuthenticateUser(string username, string password)
        {
            if (string.IsNullOrEmpty(username)
            ||  string.IsNullOrEmpty(password)
            ||  string.IsNullOrEmpty(Environment.GetEnvironmentVariable("ADMIN_USERNAME"))
            ||  string.IsNullOrEmpty(Environment.GetEnvironmentVariable("ADMIN_PASSWORD")))
            {
                return false;
            }

            return (username == Environment.GetEnvironmentVariable("ADMIN_USERNAME"))
                && (password == Environment.GetEnvironmentVariable("ADMIN_PASSWORD"));
        }
    }
}

Applications/Controllers/DiagController.cs
namespace UACloudTwin.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    [Authorize]
    public class DiagController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Applications/Controllers/SetupController.cs
namespace UACloudTwin.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using System;
    using UACloudTwin.Interfaces;
    using UACloudTwin.Models;

    [Authorize]
    public class SetupController : Controller
    {
        private readonly IDigitalTwinClient _twinclient;

        public SetupController(IDigitalTwinClient twinClient)
        {
            _twinclient = twinClient;
        }

        public ActionResult Index()
        {
            SetupModel adtModel = new SetupModel
            {
                StatusMessage = ""
            };

            return View("Index", adtModel);
        }

        public ActionResult Privacy()
        {
            return View("Privacy");
        }

        [HttpPost]
        public ActionResult Apply(string instanceUrl, string endpoint)
        {
            try
            {
                _twinclient.Login(instanceUrl);

                // check if an endpoint was supplied by the user
                if (!string.IsNullOrEmpty(endpoint))
                {
                    string[] parts = endpoint.Split(';');

                    // potentionally overwrite config settings we now know the values for
                    Environment.SetEnvironmentVariable("BROKER_USERNAME", "$ConnectionString");
                    Environment.SetEnvironmentVariable("BROKER_PASSWORD", endpoint);
                    Environment.SetEnvironmentVariable("BROKER_PORT", "9093");

                    string brokerName = parts[0].Substring(parts[0].IndexOf('=') + 6).TrimEnd('/');
                    Environment.SetEnvironmentVariable("BROKER_NAME", brokerName);

                    if (brokerName.StartsWith("iothub"))
                    {
                        Environment.SetEnvironmentVariable("TOPIC", parts[3].Substring(parts[3].IndexOf('=') + 1));
                        Environment.SetEnvironmentVariable("METADATA_TOPIC", "");
                    }
                }

                SetupModel adtModel = new SetupModel
                {
                    StatusMessage = "Settings applied successfully!"
                };

                return View("Index", adtModel);
            }
            catch (Exception ex)
            {
                SetupModel adtModel = new SetupModel
                {
                    StatusMessage = ex.Message
                };

                return View("Index", adtModel);
            }
        }
    }
}

Applications/Views/Diag/Index.cshtml
@using UACloudTwin.Models

@{
    ViewData["Title"] = "Diagnostics";
}

<h1>@ViewData["Title"]</h1>

<p>
    <div class="chart-container" width="600" height="400">
        <canvas id="myChart"></canvas>
    </div>
</p>
<p>
    <div id="table" width="600">Please wait while we collect diagnostics data...</div>
</p>

@section scripts {
    <script src="~/js/Chart.js/chart.js"></script>
    <script>

        const config = {
            type: 'line',
            options: {
                spanGaps: true,
                responsive: true,
                plugins: {
                    legend: {
                        position: 'top',
                    },
                    title: {
                        display: false,
                        text: ''
                    }
                }
            }
        };

        const CHART_COLORS = {
            red: 'rgb(255, 0, 0)',
            magenta: 'rgb(255, 0, 255)',
            yellow: 'rgb(255, 255, 0)',
            green: 'rgb(0, 128, 0)',
            blue: 'rgb(0, 0, 255)',
            cyan: 'rgb(0, 255, 255)',
            grey: 'rgb(128, 128, 128)',
            black: 'rgb(0, 0, 0)',
            silver: 'rgb(192, 192, 192)',
            lime: 'rgb(0, 255, 0)',
            maroon: 'rgb(128, 0, 0)',
            olive: 'rgb(128, 128, 0)',
            purple: 'rbg(128, 0, 128)',
            teal: 'rgb(0, 128, 128)',
            navy: 'rgb(0, 0, 128)'
        };

        const NAMED_COLORS = [
            CHART_COLORS.red,
            CHART_COLORS.magenta,
            CHART_COLORS.yellow,
            CHART_COLORS.green,
            CHART_COLORS.blue,
            CHART_COLORS.cyan,
            CHART_COLORS.grey,
            CHART_COLORS.black,
            CHART_COLORS.silver,
            CHART_COLORS.lime,
            CHART_COLORS.maroon,
            CHART_COLORS.olive,
            CHART_COLORS.purple,
            CHART_COLORS.teal,
            CHART_COLORS.navy
        ];

        function namedColor(index) {
            return NAMED_COLORS[index % NAMED_COLORS.length];
        }

        var myChart = new Chart(document.getElementById('myChart'), config);

        $(async function ()
        {
            // connection to SignalR hub
            const connection = new signalR.HubConnectionBuilder()
                .withUrl("/statusHub")
                .configureLogging(signalR.LogLevel.Information)
                .build();

            // add dataset function
            connection.on("addDatasetToChart", function(name)
            {
                var found = false;
                for (var j = 0; j < myChart.data.datasets.length; j++)
                {
                    if (myChart.data.datasets[j].label == name)
                    {
                        found = true;
                        break;
                    }
                }

                if (!found)
                {
                    const dsColor = namedColor(myChart.data.datasets.length);
                    const newDataset = {
                        label: name,
                        borderColor: dsColor,
                        cubicInterpolationMode: 'monotone',
                        tension: 0.5,
                        borderwidth: 3
                    };
                    myChart.data.datasets.push(newDataset);

                    myChart.update();
                }
            });

            // add data function
            connection.on("addDataToChart", function(timestamp, values)
            {
                myChart.data.labels.push(timestamp);
                if (myChart.data.labels.length > 100)
                {
                    myChart.data.labels.shift();
                }

                for (var j = 0; j < myChart.data.datasets.length; j++)
                {
                    var value = parseFloat(values[j].replace(',', '.'));
                    myChart.data.datasets[j].data.push(value);
                    if (myChart.data.datasets[j].data.length > 100)
                    {
                        myChart.data.datasets[j].data.shift();
                    }
                }

                myChart.update();
            });

            // add table function
            connection.on("addTable", function(html)
            {
                $('#table').html(html);
            });

            // start/continue the connection
            async function establishSignalRConnection()
            {
                try
                {
                    await connection.start();
                    console.log("Connection to SignalR Status Hub successfull established.");
                } catch (err) {
                    console.warn("Error creating SignalR connection, retry in 5 seconds %o", err);
                    setTimeout(async () => { await establishSignalRConnection(); }, 5000);
                }
            };

            connection.onclose(async () => { await establishSignalRConnection(); });

            // start the connection
            await establishSignalRConnection();
        });

    </script>
}

Applications/Views/Setup/Index.cshtml
@using UACloudTwin.Models
@model SetupModel

@{
    ViewData["Title"] = "Settings";
}

<h1>@ViewData["Title"]</h1>

<div class="row browser_top_container">
    @using (Html.BeginForm("Apply", "Setup"))
    {
    <div class="browser_connect_selection_textbox">
        <p>
            This app creates the connection between an MQTT or Kafka broker and a Digital Twin service and applies OPC UA messages to digital twins.<br/>
        </p>
        <p>
            Please provide a connection string for the broker. Alternatively, you can define environment variables (see readme).<br />
            @Html.TextBox("endpoint", (Context.Request.Query.ContainsKey("endpoint") ? Context.Request.Query["endpoint"] : (string)null), new { style = "width:100%;" })<br />
        <p />
        <p>
            Please provide an instance Url to your Digital Twin service<br />
            @Html.TextBox("instanceUrl", (Context.Request.Query.ContainsKey("instanceUrl") ? Context.Request.Query["instanceUrl"] : (string)null), new { style = "width:100%;" })<br />
        <p />
        <p>
            <input id="uploadButton" class="btn btn-primary btn_browser" type="submit" value="Apply">
        <p />
        <p>
            <b>@Model.StatusMessage</b>
        </p>
    </div>
    }
 </div>

Applications/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UA Cloud Twin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-table/bootstrap-table.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Diag" asp-action="Index">UA Cloud Twin</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Setup" asp-action="Index">Settings</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - UA Cloud Twin - <a asp-area="" asp-controller="Setup" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap-table/bootstrap-table.min.js"></script>
    <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
    <script src="~/js/aspnet-signalr/signalr.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>